
name : webilicious development

on:
  push:
    branches:
    - development
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: "Checkout source code"
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        version: 18.x
        
    - name: Build the site
      run: |
        npm i
        npm run build
    - name: Deploy to netlify
      # You may pin to the exact commit or the version.
      # uses: nwtgck/actions-netlify@5da65c9f74c7961c5501a3ba329b8d0912f39c03
      uses: nwtgck/actions-netlify@v2.0.0
      with:
          # Publish directory
          publish-dir: './public'
          production-branch: development
          deploy-message: '${{ github.event.head_commit.message }}'
      env:
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID_DEV}}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
